apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazing-components-deployment
  labels:
    app: blazing-components-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blazing-components
  template:
    metadata:
      labels:
        app: blazing-components
    spec:
      containers:
      - name: blazing-components
        image: mewgrammer/blazing-components:latest
        ports:
        - containerPort: 80
